[project]
name = "care_reports"
version = "0.1.0"
description = "A CARE backend plugin."
readme = "README.md"
authors = [
  {name = "care-ecosystem", email = "jagan.kumar@egovernments.org"} 
]
maintainers = [
  {name = "care-ecosystem", email = "jagan.kumar@egovernments.org"} 
]
license = {text = "MIT"}
dependencies = [
    "django",
    "celery",
    "djangorestframework",
]
requires-python = ">= 3.10"

[project.optional-dependencies]
test = [
    "ruff",
]

[project.urls]
bugs = "https://github.com/care-ecosystem/care_reports/issues"
homepage = "https://github.com/care-ecosystem/care_reports"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "UP",
]

[tool.uv]
package = true
